name: Build and deploy main branch
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/install-dependencies
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --since
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/install-dependencies
      - name: Lint
        run: yarn lint
  deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: "!contains(github.event.head_commit.message, 'chore: publish')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install dependencies
        uses: ./.github/install-dependencies
      - name: Configure Git
        run: |
          git --version
          git config --global user.email alex@leanjs.com
          git config --global user.name leanjsbot
          git remote rm origin
          git remote add origin "https://alexlbr:$GITHUB_TOKEN@github.com/leanjs/leanjs.git"
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GH_TOKEN }}
      - name: Build changed
        run: yarn build
      - name: Authenticate with NPM
        run: |
          yarn logout
          echo "@leanjs:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Version and publish
        run: |
          npm whoami
          yarn ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.ADMIN_GH_TOKEN }}
