name: Build and deploy website
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - website/**

permissions:
  contents: write

jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/install-dependencies
      - name: Build
        run: yarn lerna run build --scope @leanjs/website
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website/build
